### ISSUE TITLE
インフラ構築(技術テスト)

### ISSUE THREAD

**Issue by GoRuGoo** [youngeek-0410/candle-backend#2]
## 概要

インフラがしっかり立つのかという懸念点があったので本番環境のインフラ構築かつ、技術検証も兼ねてTypeScriptのAWS CDKを用いてインフラの構成をしていただきたい

### 使用技術

- CloudFront
- S3
- Lambda
- APIGateway
- PlanetScale

### 要件

- 画像のGETリクエストが来たときにS3から配信できるか
    - また、同じ画像をリクエストした際にCacheが適用されているか確認
- 画像のPOSTリクエストが来た際に適切にS3に画像を保存できるか
- 適当な値をDB書き込み、取得できるかどうか
    - DBへのデータ書き込みPOST status200
    - DBのデータ取得 status200

ができるかの確認

**Comment by fuu38** [comment]
https://dev.classmethod.jp/articles/planetscale-latency/
https://zenn.dev/taroman_zenn/articles/3d03c3030e3bf2

**Comment by GoRuGoo** [comment]
## 追加要件
ページネーションルーティングのようにURLに対応したディレクトリにGoで書かれたLambdaファイルをcdk deployすれば反映されるようにしていただきたい

**Comment by fuu38** [comment]
すっかり忘れ去られていたけど終わったので閉じる
