### ISSUE TITLE
ローカル開発環境構築

### ISSUE THREAD

**Issue by GoRuGoo** [youngeek-0410/candle-backend#3]
## 概要

技術検証及び今後の開発にローカルでの環境構築が必要になってくるので開発環境の構築をする

## 実装内容

- ローカルでLambdaを実行できること
- AWS CDKで構成したインフラにDockerを乗っけるだけで動くようになること
    - 参考:https://xp-cloud.jp/blog/2020/10/15/8936/

**Comment by fuu38** [comment]
CDKでコード書いてSAMでローカル実行，みたいな黒魔術するくらいなら，cdk watchコマンドでhotswapしたほうが絶対良いと思う．
正直IaC使う以上コマンド一つでアプリケーション建つんだから，クラウドの環境汚して開発してもいいのかなーって思ってる．特にハッカソンにおいては．

**Comment by GoRuGoo** [comment]
@fuu38 
実際に動いているサービスだったら渋いけどハッカソンならもう書いたコード直接インフラに適用してあげればいいということでしょうか？
確かにそれでもいいですね！
あまりAWS CDKに詳しく無いのであっているかわからないですが、開発してcdk watchして本番環境にデプロイしちゃってテストという感じでしょうか？

**Comment by fuu38** [comment]
ベストなのは開発者個人ごとの環境で`cdk watch`しながら開発し、本番環境はCI/CD経由だけでデプロイするみたいな流れかな。

>ハッカソンならもう書いたコード直接インフラに適用してあげればいいということでしょうか？
概ねその認識だけど、最終的にはCI/CD通してデプロイかな。本番環境でテストしながら開発して、完成したらCI/CD通して(=cdkコマンドで)デプロイして環境をきれいにするイメージ。

**Comment by is-hoku** [comment]
方針が変わり以下のようになった。
https://github.com/youngeek-0410/candle-backend/issues/3#issuecomment-1846793270
