### ISSUE TITLE
インフラテスト用Goコード実装

### ISSUE THREAD

**Issue by GoRuGoo** [youngeek-0410/candle-backend#4]
#2 を実装するに当たってGoのコードが必要になるので実装していただきたいです。
内容は #2 を参照してください。

**Comment by is-hoku** [comment]
@GoRuGoo ここで言っている Go のコードというのは、#2 の動作が実現できるような Lambda を実装するということで合ってる？

**Comment by fuu38** [comment]
これ#2 俺が先にやって「あとはLambdaのコード追加するだけですよ」的な状態まで持っていく必要があるって認識でOK?

**Comment by is-hoku** [comment]
僕は Lambda から S3 にアクセスして、画像の取得・アップロードができる関数を作れば良いということ？
PlanetScale とのやりとりとか、Congnito も必要？

**Comment by fuu38** [comment]
cognitoは忘れてた、Planetscaleはどうしような...
開発前にそもそもAWSのアカウント作んなきゃ行けなかったりするしこれ今日中はきついな
誰が環境持つとか考えなきゃだから21時のMTGでそれも話したいな

**Comment by is-hoku** [comment]
技術構成が変更され、エンドポイントが決まったので、各自 API を生やしていく方針になった。
